/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./src/components/Upload/AvatarUpload.vue')['default']
    CenterEchart: typeof import('./src/components/Home/centerEchart.vue')['default']
    Drafts: typeof import('./src/components/Email/Drafts.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    LeftEchart: typeof import('./src/components/Home/leftEchart.vue')['default']
    LeftEchartBottom: typeof import('./src/components/Home/leftEchartBottom.vue')['default']
    MapEchart: typeof import('./src/components/Home/mapEchart.vue')['default']
    ReceivedEmail: typeof import('./src/components/Email/ReceivedEmail.vue')['default']
    RightEchart: typeof import('./src/components/Home/rightEchart.vue')['default']
    RightEchartBottom: typeof import('./src/components/Home/rightEchartBottom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDiv: typeof import('./src/components/Until/ScrollDiv.vue')['default']
    SendEmail: typeof import('./src/components/Email/SendEmail.vue')['default']
    UserCenter: typeof import('./src/components/Email/UserCenter.vue')['default']
  }
}
