/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./src/components/Upload/AvatarUpload.vue')['default']
    Category: typeof import('./src/components/Wallpaper/Category.vue')['default']
    Diolog: typeof import('./src/components/Until/Diolog.vue')['default']
    Drafts: typeof import('./src/components/Email/Drafts.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HomeContain: typeof import('./src/components/Home/HomeContain.vue')['default']
    HomeUser: typeof import('./src/components/Home/HomeUser.vue')['default']
    NewList: typeof import('./src/components/News/NewList.vue')['default']
    Panination: typeof import('./src/components/Until/Panination.vue')['default']
    ReceivedEmail: typeof import('./src/components/Email/ReceivedEmail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDiv: typeof import('./src/components/Until/ScrollDiv.vue')['default']
    SendEmail: typeof import('./src/components/Email/SendEmail.vue')['default']
    Theme: typeof import('./src/components/Theme/index.vue')['default']
    UserCenter: typeof import('./src/components/Email/UserCenter.vue')['default']
    WallpaperList: typeof import('./src/components/Wallpaper/WallpaperList.vue')['default']
  }
}
