const SUCCESS_CODE = 200;
const ERROR_CODE = 500;
const NOT_FOUND_CODE = 404;
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN_CODE = 403;

//导出
module.exports = {
  SUCCESS_CODE,
  ERROR_CODE,
  NOT_FOUND_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
};
