/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CenterEchart: typeof import('./src/components/Home/centerEchart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    LeftEchart: typeof import('./src/components/Home/leftEchart.vue')['default']
    LeftEchartBottom: typeof import('./src/components/Home/leftEchartBottom.vue')['default']
    MapEchart: typeof import('./src/components/Home/mapEchart.vue')['default']
    Received: typeof import('./src/components/Email/Received.vue')['default']
    ReceivedEmail: typeof import('./src/components/Email/ReceivedEmail.vue')['default']
    RightEchart: typeof import('./src/components/Home/rightEchart.vue')['default']
    RightEchartBottom: typeof import('./src/components/Home/rightEchartBottom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDiv: typeof import('./src/components/Until/ScrollDiv.vue')['default']
  }
}
