/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CenterEchart: typeof import('./src/components/Home/centerEchart.vue')['default']
    Drafts: typeof import('./src/components/Email/Drafts.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EmailPanel: typeof import('./src/components/Email/EmailPanel.vue')['default']
    LeftEchart: typeof import('./src/components/Home/leftEchart.vue')['default']
    LeftEchartBottom: typeof import('./src/components/Home/leftEchartBottom.vue')['default']
    MapEchart: typeof import('./src/components/Home/mapEchart.vue')['default']
    ReceivedEmail: typeof import('./src/components/Email/ReceivedEmail.vue')['default']
    RightEchart: typeof import('./src/components/Home/rightEchart.vue')['default']
    RightEchartBottom: typeof import('./src/components/Home/rightEchartBottom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDiv: typeof import('./src/components/Until/ScrollDiv.vue')['default']
    SendEmail: typeof import('./src/components/Email/SendEmail.vue')['default']
    UserCenter: typeof import('./src/components/Email/UserCenter.vue')['default']
  }
}
